---
title: "p8105_hw6"
output: github_document
date: "2024-12-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(broom)
library(modelr)
```

## **Problem 1**

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

set.seed(123) 

bootstrap_results = 
  replicate(
  n = 5000, 
  expr = {
    boot_sample <- weather_df %>% sample_frac(replace = TRUE)
    model <- lm(tmax ~ tmin, data = boot_sample)
    glance_out <- glance(model)
    tidy_out <- tidy(model)
    
    r_squared <- glance_out$r.squared
    log_b0_b1 <- log(tidy_out$estimate[1] * tidy_out$estimate[2])
    
    c(r_squared = r_squared, log_b0_b1 = log_b0_b1)
  },
  simplify = FALSE
) %>%
  bind_rows()

percentiles =
  bootstrap_results %>%
  summarize(
    r_squared_low = quantile(r_squared, 0.025),
    r_squared_high = quantile(r_squared, 0.975),
    log_b0_b1_low = quantile(log_b0_b1, 0.025),
    log_b0_b1_high = quantile(log_b0_b1, 0.975)
  )

bootstrap_results %>%
  pivot_longer(cols = everything(), names_to = "metric", values_to = "value") %>%
  ggplot(aes(x = value)) +
  geom_density(fill = "blue", alpha = 0.5) +
  facet_wrap(~metric, scales = "free") +
  theme_minimal() +
  labs(title = "Bootstrap Distributions", x = "Value", y = "Density")

```

## **Problem 2**

data import and cleaning

```{r}
homicide_data =
  read_csv(file = "./homicide-data.csv")

homicide_cleaned =
  homicide_data %>%
  mutate(
    city_state = str_c(city, state, sep = ", "),
    solved = if_else(disposition == "Closed by arrest", 1, 0),
    victim_age = as.numeric(victim_age)
  ) %>%
  filter(
    !city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"),
    victim_race %in% c("White", "Black"),
    !is.na(victim_age)
  )
```

logistic regression - baltimore

```{r}
baltimore_data =
  homicide_cleaned %>%
  filter(city_state == "Baltimore, MD")

baltimore_model =
  glm(solved ~ victim_age + victim_race + victim_sex, data = baltimore_data, family = binomial()) 

broom::tidy(baltimore_model, exponentiate = TRUE, conf.int = TRUE) %>%
  filter(term == "victim_sexMale") %>% 
  select(estimate, conf.low, conf.high)
```

logistic regression - all cities

```{r}
all_city_model =
  homicide_cleaned %>%
  nest(data = -city_state) %>%
  mutate(
    model = map(data, ~ glm(solved ~ victim_age + victim_sex + victim_race, data = ., family = binomial)),
    tidy_results = map(model, ~ tidy(., exponentiate = TRUE, conf.int = TRUE))
  ) %>%
  unnest(tidy_results) %>%
  filter(term == "victim_sexMale") %>%
  select(city_state, estimate, conf.low, conf.high)

all_city_model %>%
  arrange(estimate) %>%
  mutate(city_state = factor(city_state, levels = city_state)) %>%
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
  coord_flip() +
  theme_minimal() +
  labs(
    title = "Adjusted Odds Ratios for Male vs Female Victims by City",
    x = "City",
    y = "Adjusted Odds Ratio (with 95% CI)"
  )
```

## **Problem 3**

cleaning data and regression model
```{r}
birthweight_data =
  read_csv(file = "./birthweight.csv")

birthweight_clean =
  birthweight_data %>%
  mutate(
    babysex = factor(babysex, levels = c(1, 2), labels = c("Male", "Female")),
    malform = factor(malform, levels = c(0, 1), labels = c("Absent", "Present")),
    frace = factor(frace, levels = c(1, 2, 3, 4, 8, 9),
                   labels = c("White", "Black", "Asian", "Puerto Rican", "Other", "Unknown")),
    mrace = factor(mrace, levels = c(1, 2, 3, 4, 8),
                   labels = c("White", "Black", "Asian", "Puerto Rican", "Other"))
  ) %>%
  filter(!is.na(bwt))

fit_bwt =
  lm(bwt ~ gaweeks + blength + bhead + wtgain + smoken + ppbmi + momage + parity + malform,
  data = birthweight_clean
)

birthweight_clean =
  birthweight_clean %>%
  add_predictions(fit_bwt, var = "predicted_bwt") %>%
  add_residuals(fit_bwt, var = "residuals")
```

residual vs fitted plot
```{r}
ggplot(birthweight_clean, aes(x = predicted_bwt, y = residuals)) +
  geom_point(alpha = 0.5) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  theme_minimal() +
  labs(
    title = "Residuals vs. Fitted Values",
    x = "Fitted Values",
    y = "Residuals"
  )
```

comparisons models
```{r}
fit_length_ga = 
  lm( bwt ~ blength + gaweeks, data = birthweight_clean)

fit_interactions = 
  lm(bwt ~ bhead * blength * babysex, data = birthweight_clean)
```

